site_name: UnityChart
theme:
  name: material
  features:
      - navigation.tabs
  palette:
    scheme: slate
nav:
  - Home: index.md
  - Getting Started: GetStarted.md
  - Guides:
      - Line Chart: guides/LineChart.md
  - API Reference:
      - Runtime:
          - DataProvider: api/DataProvider.md
          - DataProviderRegistry: api/DataProviderRegistry.md
          - DataProviderOwner: api/DataProviderOwner.md
          - OwnershipScope: api/OwnershipScope.md
      - Editor:
          - LineChart: api/LineChart.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/alirezaft/UnityChart
repo_name: alirezaft/UnityChart
extra_css:
  - style.css